### ISSUE TITLE
运行最后出错了。。老哥给瞅瞅。。。

### ISSUE THREAD

**Issue by 22xiaogu** [muyeyong/movie_robot#1]
Traceback (most recent call last):
  File "/app/douban_movie_download.py", line 65, in <module>
    downloader.start()
  File "/app/src/movie/downloader.py", line 41, in start
    self.search_and_download(
  File "/app/src/movie/downloader.py", line 82, in search_and_download
    exist = self.radarr.exist_movie(imdb)
  File "/app/src/radarr/utils.py", line 27, in exist_movie
    allMovieList = self.search_all_local_movie()
  File "/app/src/radarr/utils.py", line 24, in search_all_local_movie
    return json.loads(r)
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

这是错误代码。。

**Comment by muyeyong** [comment]
search_all_local_movie 这个方法返回的内容，有问题，可以自己调试一下，或者用postman试一下

**Comment by 22xiaogu** [comment]
> 

已经好了，估计是之前一些参数没设置好，现在已经正常运行了。 大佬牛逼！
